# Generated by Django 6.0.1 on 2026-01-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_column='MAIL_USER', max_length=50)),
                ('password', models.CharField(db_column='MDP', max_length=50)),
                ('nom', models.CharField(blank=True, db_column='NM_USER', max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, db_column='PRN_USER', max_length=50, null=True)),
                ('date_connexion', models.DateTimeField(auto_now=True, db_column='DT_TC_CNX')),
            ],
            options={
                'db_table': 't_user',
                'managed': False,
            },
        ),
    ]
